##################################################
# Wolfinch Screener config
##################################################

strategies:

notifier:
   telegram:
      token: 'qZH0'
      chat-id: ''

ui:
   enabled : true
   port : 8081